### ISSUE TITLE
Datepicker default value is not reflected in the editor

### ISSUE THREAD

**Issue by skateman** [skateman/ddf-editor#2]
Somehow the [`formOptions.initialize`](https://github.com/skateman/ddf-editor/blob/master/src/Draggable/Input.jsx#L13) has no effect on datepickers :confused: it works well with any other field, so my guess is that the problem is somewhere in DDF.

**Comment by skateman** [comment]
@hyperkid123 can you please help me with this? If in the DDF editor you add a new date picker and set a default value for it while editing, the value is not reflected in the left side after saving. It works well with any other kind of field.

**Comment by Hyperkid123** [comment]
@skateman i will take a look
