### ISSUE TITLE
Toolbar inaccessible when viewport height < 600px

### ISSUE THREAD

**Issue by himdel** [skateman/ddf-editor#4]
No way to get to the bottom buttons in the toolbar when the viewport height is too small. (And it doesn't scroll with the rest.)

(The whole `.dialog-toolbox` element is 621px tall on my machine.)

It seems like...

```diff
.dialog-editor .dialog-toolbox {
     position: sticky;
     top: 0;
+    bottom: 0;
}
```

fixes that :).

**Comment by skateman** [comment]
Fixed, pushed, thanks! :+1:
