### ISSUE TITLE
Can't unset non-required dropdown value

### ISSUE THREAD

**Issue by himdel** [skateman/ddf-editor#5]
When a dropdown is not required, and has a default value, it makes sense to allow choice only between the list of values (as nil just implies the default).

But, when there is no default value,
after chosing a value in the dropdown (left side), you can no longer unchoose it.

**Comment by skateman** [comment]
Well, I think this could be implemented in the DDF, I have a feeling that patternfly even has a pattern for unselecting the value by having an `x` in the right side of the select. What do you think @hyperkid123?

**Comment by Hyperkid123** [comment]
@himdel there is prop just for this purpose `isClearable: true`

https://data-driven-forms.org/renderer/component-api#select

**Comment by skateman** [comment]
Gonna use it, thanks!

**Comment by skateman** [comment]
@himdel are you okay with having this option for required dropdowns as well? It would allow to invalidate the field, but the validator would catch it anyway

**Comment by himdel** [comment]
Sure, feels more consistent that way :)
