### ISSUE TITLE
Dropdowns - n.value.includes is not a function

### ISSUE THREAD

**Issue by himdel** [skateman/ddf-editor#6]
Edit a dropdown,
change types to numeric, fix the values, Save.
Edit it again, change to multiselect, Save.
Pick a value on the left side...
the whole screen disappears :).

```bundle.js:6 Uncaught TypeError:  n.value.includes is not a function```

I think the order can be different, you can also first pick a value and then change to multiselect and save.

**Comment by skateman** [comment]
Yeah, I think this is a bug in DDF. Creating an issue there to track it.

**Comment by skateman** [comment]
BTW, I'm still thinking about making the left side not editable at all. It is a little confusing.

**Comment by himdel** [comment]
> BTW, I'm still thinking about making the left side not editable at all. It is a little confusing.

Yeaah, maybe it should only be editable that way in the View mode, not Edit mode.
And leave Edit mode just for editing the properties.

(But then the naming is potentially confusing, as the fields are not editable in edit mode :D, Design/Preview modes?)

**Comment by skateman** [comment]
Text can't be longer in the switch, otherwise it crashes on smaller resolutions.

**Comment by himdel** [comment]
✍️ | 👁️ ? :) OK, I don't know :)
